### ISSUE TITLE
Having troubles getting this working

### ISSUE THREAD

**Issue by ghost** [CalebAlbers/IT-Glue-API-PowerShell-Wrapper#5]
I have set the base uri.
I have added my api key.
I've exported settings.

When I run a cmdlet to test, it errors out:

PS C:\Users\dlee> Get-ITGlueUsers
Invoke-RestMethod : Specified value has invalid Control characters.
Parameter name: value
At C:\Users\dlee\Documents\WindowsPowerShell\Modules\ITGlueAPI\Resources\Users.ps1:48 char:20
+ ... st_output = Invoke-RestMethod -method "GET" -uri ($ITGlue_Base_URI +  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

It doesn't seem like it's an api key issue.  As I have ran the command without an api key and the error is different.

**Comment by CalebAlbers** [comment]
Hey Dennison!

What OS and what version of PowerShell are you running? Try using `$PSVersionTable.PSVersion` to get the PowerShell major and minor version.

I have a few troubleshooting items to try:

- Could you try running `Get-ITGlueBaseURI` and ensuring it is correct?
- When you run `Get-ITGlueAPIKey`, do you get `System.Security.SecureString` as the output?
- Try running `(New-Object System.Management.Automation.PSCredential 'N/A', $ITGlue_API_Key).GetNetworkCredential().Password`. Does it return your unencrypted API key?

Let me know how those work and we can go from there.

Cheers,
-Caleb

**Comment by ghost** [comment]
Thanks for the tips.  I think I got it figured.

I tried pasting the api key in and that failed.  Then a lot of trial an error typing it in trying to differentiate the ones and the lower case L’s and capital O vs zero.

It’s working now.


dennison lee . senior consultant

T 604.682.3444
F 604.682.3448
www.yournucleus.ca<http://www.yournucleus.ca/>

NUCLEUS NETWORKS INC.
425 HORNBY STREET
VANCOUVER  BC  V6C 2Y2

**Comment by CalebAlbers** [comment]
Good deal. Let me know if you need anything.
